version: '2'

services:
  gpu:
    build: ./gpu
    privileged: true
  cuda:
    build: ./cuda
    privileged: true
    depends_on: 
     - gpu 
  app:
    build: ./app
    privileged: true
    depends_on: 
      - gpu 
  nv-pytorch:
    build: ./nvidia-base-image
    privileged: true
    depends_on: 
      - gpu 
